version: 2
jobs:
  build-devs:
    docker:
      - image: php:7.0-apache
    working_directory: /home/saintmedia/
    steps:
      - checkout
      - run:
          name: Install System Packages
          command: |
            apt-get update && apt-get -y install zip
            apt-get --quiet install --yes python-pip
            pip install -U pip
            pip install awscli
      - run:
          name: Zip Code
          command: |
            cd www/callcenter && zip -r callcenter.zip .
            cd ../work && zip -r work.zip .
            cd ../admin && zip -r admin.zip .
            cd ../admin_master && zip -r admin_master.zip .
      - run:
          name: Upload Code to S3
          command: |
            aws s3 cp www/callcenter/callcenter.zip s3://tst-cd-willgroup/callcenter.zip
            aws s3 cp www/work/work.zip s3://tst-cd-willgroup/work.zip
            aws s3 cp www/admin/admin.zip s3://tst-cd-willgroup/admin.zip
            aws s3 cp www/admin_master/admin_master.zip s3://tst-cd-willgroup/admin_master.zip
      - deploy:
          name: Deploy to Development Server
          command: |
            aws deploy create-deployment --application-name callcenter --deployment-group-name callcenter --deployment-config-name CodeDeployDefault.AllAtOnce --s3-location bucket=tst-cd-willgroup,bundleType=zip,key=callcenter.zip --region ap-northeast-1
            aws deploy create-deployment --application-name work --deployment-group-name work --deployment-config-name CodeDeployDefault.AllAtOnce --s3-location bucket=tst-cd-willgroup,bundleType=zip,key=work.zip --region ap-northeast-1
            aws deploy create-deployment --application-name admin --deployment-group-name admin --deployment-config-name CodeDeployDefault.AllAtOnce --s3-location bucket=tst-cd-willgroup,bundleType=zip,key=admin.zip --region ap-northeast-1
            aws deploy create-deployment --application-name admin_master --deployment-group-name admin_master --deployment-config-name CodeDeployDefault.AllAtOnce --s3-location bucket=tst-cd-willgroup,bundleType=zip,key=admin_master.zip --region ap-northeast-1
  build-prd:
    docker:
      - image: php:7.0-apache
    working_directory: /home/saintmedia/
    steps:
      - checkout
      - run:
          name: Install System Packages
          command: |
            apt-get update && apt-get -y install zip
            apt-get --quiet install --yes python-pip
            pip install -U pip
            pip install awscli
      - run:
          name: Zip Code
          command: |
            cd www/callcenter && zip -r prd-callcenter.zip .
            cd ../work && zip -r prd-work.zip .
            cd ../admin && zip -r prd-admin.zip .
            cd ../admin_master && zip -r prd-admin_master.zip .
      - run:
          name: Upload Code to S3
          command: | 
            aws s3 cp www/callcenter/callcenter-prd.zip s3://tst-cd-willgroup/callcenter-prd.zip
            aws s3 cp www/work/work-prd.zip s3://tst-cd-willgroup/work-prd.zip
            aws s3 cp www/admin/admin-prd.zip s3://tst-cd-willgroup/admin-prd.zip
            aws s3 cp www/admin_master/admin_master-prd.zip s3://tst-cd-willgroup/admin_master-prd.zip
      - deploy:
          name: Deploy to Production Server
          command: |
            aws deploy create-deployment --application-name callcenter --deployment-group-name prd-callcenter --deployment-config-name CodeDeployDefault.AllAtOnce --s3-location bucket=tst-cd-willgroup,bundleType=zip,key=prd-callcenter.zip --region ap-northeast-1
            aws deploy create-deployment --application-name work --deployment-group-name prd-work --deployment-config-name CodeDeployDefault.AllAtOnce --s3-location bucket=tst-cd-willgroup,bundleType=zip,key=prd-work.zip --region ap-northeast-1
            aws deploy create-deployment --application-name admin --deployment-group-name prd-admin --deployment-config-name CodeDeployDefault.AllAtOnce --s3-location bucket=tst-cd-willgroup,bundleType=zip,key=prd-admin.zip --region ap-northeast-1
            aws deploy create-deployment --application-name admin_master --deployment-group-name prd-admin_master --deployment-config-name CodeDeployDefault.AllAtOnce --s3-location bucket=tst-cd-willgroup,bundleType=zip,key=prd-admin_master.zip --region ap-northeast-1
workflows:
  version: 2
  build-test-and-approval-deploy:
    jobs:
      - build-devs
      - hold:
          type: approval
          requires:
            - build-devs
      - build-prd:
          requires:
            - hold
          filters:
            branches:
              only: production
