version: 2
jobs:
  build-devs:
    docker:
      - image: php:7.0-apache
    working_directory: /home/saintmedia/
    steps:
      - checkout
      - run:
          name: Install System Packages
          command: |
            apt-get update && apt-get -y install zip
            apt-get --quiet install --yes python-pip
            pip install -U pip
            pip install awscli
      - run:
          name: Zip Code
          command: |
            cd www/callcenter && zip -r callcenter.zip .
            cd ../work && zip -r work.zip .
            cd ../admin && zip -r admin.zip .
            cd ../admin_master && zip -r admin_master.zip .
      - run:
          name: Upload Code to S3
          command: |
            aws s3 cp www/callcenter/callcenter.zip s3://tst-cd-willgroup1/callcenter.zip
            aws s3 cp www/work/work.zip s3://tst-cd-willgroup1/work.zip
            aws s3 cp www/admin/admin.zip s3://tst-cd-willgroup1/admin.zip
            aws s3 cp www/admin_master/admin_master.zip s3://tst-cd-willgroup1/admin_master.zip
      - deploy:
          name: Deploy to Development Server
          command: aws deploy create-deployment --application-name callcenter --deployment-group-name callcenter --deployment-config-name CodeDeployDefault.AllAtOnce --s3-location bucket=tst-cd-willgroup1,bundleType=zip,key=callcenter.zip --region ap-southeast-1
  build-prd:
    docker:
      - image: php:7.0-apache
    working_directory: /home/saintmedia/
    steps:
      - checkout
      - run:
          name: Install System Packages
          command: |
            apt-get update && apt-get -y install zip
            apt-get --quiet install --yes python-pip
            pip install -U pip
            pip install awscli
      - run:
          name: Zip Code
          command: |
            cd www/callcenter && zip -r callcenter-prd.zip .
            cd ../work && zip -r work-prd.zip .
            cd ../admin && zip -r admin-prd.zip .
            cd ../admin_master && zip -r admin_master-prd.zip .
      - run:
          name: Upload Code to S3
          command: | 
            aws s3 cp www/callcenter/callcenter-prd.zip s3://tst-cd-willgroup1/callcenter-prd.zip
            aws s3 cp www/work/work-prd.zip s3://tst-cd-willgroup1/work-prd.zip
            aws s3 cp www/admin/admin-prd.zip s3://tst-cd-willgroup1/admin-prd.zip
            aws s3 cp www/admin_master/admin_master-prd.zip s3://tst-cd-willgroup1/admin_master-prd.zip
      - deploy:
          name: Deploy to Production Server
          command: aws deploy create-deployment --application-name callcenter_prd --deployment-group-name callcenter_prd --deployment-config-name CodeDeployDefault.AllAtOnce --s3-location bucket=tst-cd-willgroup1,bundleType=zip,key=callcenter-prd.zip --region ap-southeast-1
workflows:
  version: 2
  build-test-and-approval-deploy:
    jobs:
      - build-devs:
          filters:
            branches:
              only: devlops
      - hold:
          type: approval
          requires:
            - build-devs
      - build-prd:
          requires:
            - hold
          filters:
            branches:
              only: production